all: attack1 attack2 attack3 attack4
attack1: attack1.c
	gcc -o attack1 attack1.c
attack2: attack2.c
	gcc -o attack2 attack2.c
attack3: attack3.c
	gcc -o attack3 attack3.c
attack4: attack4.c
	gcc -o attack4 attack4.c